# Comandos:
# docker compose up mysql # iniciar el contenedor
# docker compose up mysql -d # inicar pero desenlazado
# docker compose down # detener contenedor

# composer
services:
  mysql:
    image: mysql:8.0
    container_name: mysql-test-my_database
    hostname: database
    restart: no
    environment:
      MYSQL_ROOT_PASSWORD: 12340
      MYSQL_DATABASE: pizzeria
      MYSQL_USER: marimaro
      MYSQL_PASSWORD: 1234
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
